name: webmedia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.1.0
  firebase_auth: 4.0.2
  dio: ^4.0.6
  cloud_firestore: 4.0.2
  email_validator: ^2.0.1
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  http: ^0.13.5
  flutter: 
    sdk: flutter
  intl: ^0.17.0
  json_model: ^1.0.0
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  badges: ^2.0.3

  
  

dev_dependencies: 
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

